services:
  api:
    build: .
    image: api:1.0
    ports:
      - '3000:3000'
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: banco_teste
      MYSQL_USER: bertolo
      MYSQL_PASSWORD: bertolo123
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  mysql-data:
    driver: local
